#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('spec:generators') do |spec|
  spec.pattern = FileList['spec/generators/*_spec.rb']
end

RSpec::Core::RakeTask.new('spec:javascripts') do |spec|
  spec.pattern = FileList['spec/javascripts/*_spec.rb']
end

TestApp::Application.load_tasks
